# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在学校'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='school_short',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='学校缩写'),
        ),
    ]
