# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_auto_20180711_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='allow_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='批量添加账号数量'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='create_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当前可创建剩余数量'),
        ),
    ]
