# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_auto_20180803_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id_num',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='用户名（工号/学号）'),
        ),
    ]
