# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-07-18 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0024_auto_20211221_1443'),
        ('judge', '0004_auto_20190819_1536'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('ducheng', '填空题')], default='choice', max_length=10, verbose_name='题型')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('student_answer', models.CharField(blank=True, default='', max_length=500, verbose_name='学生答案')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'db_table': 'quiz_answer_record',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='作业标题')),
                ('question_count', models.IntegerField(default=5, verbose_name='要求答题数')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('banji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.BanJi', verbose_name='目标班级')),
                ('kp2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.KnowledgePoint2', verbose_name='指定知识点')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='布置教师')),
            ],
            options={
                'verbose_name': '知识点作业',
                'verbose_name_plural': '知识点作业',
                'db_table': 'quiz_assignment',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.QuizAssignment', verbose_name='所属作业'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='banji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.BanJi', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='choice_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.ChoiceProblem', verbose_name='选择题'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='ducheng_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.DuchengProblem', verbose_name='填空题'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='kp2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.KnowledgePoint2', verbose_name='所属二级知识点'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
    ]
