# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-07-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizassignment',
            name='choice_count',
            field=models.IntegerField(default=0, verbose_name='选择题数量'),
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='ducheng_count',
            field=models.IntegerField(default=0, verbose_name='填空题数量'),
        ),
    ]
