# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-07-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20260719_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='points',
            field=models.FloatField(default=0, verbose_name='获得积分'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='round_num',
            field=models.IntegerField(default=1, verbose_name='第几轮'),
        ),
    ]
