# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-07-24 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20260723_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizassignment',
            name='banji',
        ),
        migrations.RemoveField(
            model_name='quizassignment',
            name='kp2',
        ),
        migrations.RemoveField(
            model_name='quizassignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='answerrecord',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='QuizAssignment',
        ),
    ]
