# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_myhomework_allow_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='resubmit_number',
            field=models.IntegerField(default=100, verbose_name='提交次数限制'),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='remained_number',
            field=models.IntegerField(default=100, verbose_name='提交次数限制'),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='resubmit_number',
            field=models.IntegerField(default=100, verbose_name='提交次数限制'),
        ),
    ]
