# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20180516_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='allow_random',
            field=models.BooleanField(default=True, verbose_name='是否打乱选择题选项顺序>？'),
        ),
    ]
