# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-16 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_homework_allow_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='allow_random',
        ),
    ]
