# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20180516_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='show_answer',
            field=models.CharField(default='每次提交后', max_length=20, verbose_name='何时显示答案'),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='show_answer',
            field=models.CharField(default='每次提交后', max_length=20, verbose_name='何时显示答案'),
        ),
    ]
