# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20190721_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='ducheng_problem_ids',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='读程题id列表'),
        ),
        migrations.AddField(
            model_name='homework',
            name='ducheng_problem_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='show_score',
            field=models.CharField(default='最高分值', max_length=20, verbose_name='多次提交有效得分为'),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='ducheng_problem_score',
            field=models.IntegerField(default=0, verbose_name='填空题成绩'),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='score_list',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='总成绩列表'),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='wrong_ducheng_problems',
            field=models.CharField(default='', max_length=200, verbose_name='错误的填空题'),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='wrong_ducheng_problems_info',
            field=models.CharField(default='', max_length=200, verbose_name='错误的填空题保留信息'),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='ducheng_problem_ids',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='读程题id列表'),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='ducheng_problem_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='show_score',
            field=models.CharField(default='最高分值', max_length=20, verbose_name='多次提交有效得分为'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='score',
            field=models.FloatField(default=0, verbose_name='总成绩'),
        ),
    ]
