# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20190819_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='score_list',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='总成绩列表'),
        ),
    ]
