# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-28 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20190827_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='choice_problem_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='ducheng_problem_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='score_list',
            field=models.CharField(default='', max_length=200, verbose_name='总成绩列表'),
        ),
    ]
