# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20190828_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='total_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='myhomework',
            name='total_score',
            field=models.FloatField(),
        ),
    ]
