# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-02 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_auto_20200715_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhomework',
            name='time_allowed',
            field=models.IntegerField(null=True, verbose_name='允许时长'),
        ),
        migrations.AddField(
            model_name='temphomeworkanswer',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
