# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_auto_20201202_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='time_allowed',
            field=models.IntegerField(null=True, verbose_name='允许时长'),
        ),
    ]
