# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-22 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_homework_time_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkanswer',
            name='student_detail',
            field=models.TextField(max_length=300, null=True, verbose_name='学生点击数据'),
        ),
    ]
