# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-07-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_banji_work_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='banji',
            name='score_weight',
            field=models.CharField(default='{"pscore"=1,"mscore"=0,"sign"=0}', max_length=100, verbose_name='各项数据权重'),
        ),
    ]
