# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-07-09 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_banji_score_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banji',
            name='score_weight',
        ),
    ]
