# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-12-21 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_banji_score_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='banji',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 14, 42, 22, 676567)),
        ),
    ]
