# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-12-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_banji_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banji',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
