# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-19 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_duchengproblem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duchengproblem',
            options={'ordering': ['ducheng_id'], 'verbose_name': '填空题', 'verbose_name_plural': '填空题'},
        ),
        migrations.RemoveField(
            model_name='duchengproblem',
            name='program',
        ),
    ]
