# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-07-31 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20190819_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceproblem',
            name='explanation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='题目解析'),
        ),
        migrations.AddField(
            model_name='duchengproblem',
            name='explanation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='题目解析'),
        ),
    ]
