# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-17 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_users', models.IntegerField()),
                ('choices', models.IntegerField()),
                ('programms', models.IntegerField()),
                ('fills', models.IntegerField()),
                ('save_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pythons', models.IntegerField()),
                ('javas', models.IntegerField()),
                ('cpps', models.IntegerField()),
                ('begins', models.IntegerField()),
                ('advances', models.IntegerField()),
                ('savetime', models.DateField()),
            ],
        ),
    ]
