# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-06 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='homework',
            field=models.IntegerField(null=True),
        ),
    ]
