# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-16 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_id', models.IntegerField()),
                ('operation', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeDirHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dirText', models.TextField(verbose_name='目录序列化的结果')),
                ('contribution', models.TextField(verbose_name='贡献度')),
                ('submitTime', models.DateTimeField(auto_now_add=True)),
                ('fileHash', models.CharField(max_length=40, verbose_name='文件hash')),
            ],
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CodeWeekClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='程序设计课班级名称')),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('numberEachGroup', models.IntegerField(choices=[(1, '最多一个人'), (2, '最多两个人'), (3, '最多三个人')], default=1)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CodeWeekClassGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('counter', models.IntegerField(default=0)),
                ('using', models.BooleanField(default=True)),
                ('cwclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CodeWeekClass_group', to='code_week.CodeWeekClass')),
                ('nowCodeDir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='code_week.CodeDirHistory')),
            ],
        ),
        migrations.CreateModel(
            name='CodeWeekClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, '初始，需要分组'), (2, '加入分组'), (3, '成为组长'), (4, '可以选题'), (5, '可以提交')], default=1)),
                ('isLeader', models.BooleanField(default=False)),
                ('codeWeekClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CodeWeekClass_student', to='code_week.CodeWeekClass')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Group_member', to='code_week.CodeWeekClassGroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeZipFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.TextField(verbose_name='文件名')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30, verbose_name='题目类别')),
            ],
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Report_history', to='code_week.CodeWeekClassGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ShejiProblem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False, verbose_name='题目id')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('editorText', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(max_length=200, null=True, verbose_name='文件名')),
                ('content_type', models.CharField(max_length=200, verbose_name='文件类型')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改时间')),
                ('in_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_week.ProblemCategory', verbose_name='题目类别')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShejiProblem_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['problem_id'],
                'verbose_name': '程序设计题',
                'verbose_name_plural': '程序设计题',
            },
        ),
        migrations.CreateModel(
            name='TarHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarTime', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_week.CodeWeekClass')),
            ],
        ),
        migrations.AddField(
            model_name='codeweekclassgroup',
            name='selectedProblem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GroupSelectProblem', to='code_week.ShejiProblem'),
        ),
        migrations.AddField(
            model_name='codeweekclass',
            name='problems',
            field=models.ManyToManyField(related_name='CodeWeekClass_problems', to='code_week.ShejiProblem'),
        ),
        migrations.AddField(
            model_name='codeweekclass',
            name='students',
            field=models.ManyToManyField(through='code_week.CodeWeekClassStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codeweekclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CodeWeekClass_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codefile',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Group_codefile', to='code_week.CodeWeekClassGroup'),
        ),
        migrations.AddField(
            model_name='codedirhistory',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Code_history', to='code_week.CodeWeekClassGroup'),
        ),
        migrations.AddField(
            model_name='codedirhistory',
            name='zipFile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='code_week.CodeZipFile'),
        ),
        migrations.AddField(
            model_name='classoperation',
            name='cwclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Class_operations', to='code_week.CodeWeekClass'),
        ),
    ]
