# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-11-10 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_week', '0002_latestinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedirhistory',
            name='isUsing',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='codeweekclassgroup',
            name='mergeCodeDir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MergeCodeZip', to='code_week.CodeDirHistory'),
        ),
        migrations.AlterField(
            model_name='codedirhistory',
            name='contribution',
            field=models.TextField(null=True, verbose_name='贡献度'),
        ),
        migrations.AlterField(
            model_name='codeweekclassgroup',
            name='nowCodeDir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NowCodeZip', to='code_week.CodeDirHistory'),
        ),
    ]
