# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_week', '0003_auto_20211110_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeweekclass',
            name='numberEachProblem',
            field=models.IntegerField(choices=[(1, '最多一个组选'), (2, '最多两个组选'), (3, '最多三个组选'), (4, '最多四个组选'), (5, '最多五个组选'), (6, '最多六个组选'), (7, '最多七个组选'), (8, '最多八个组选'), (9, '最多九个组选'), (10, '最多十个组选')], default=3),
        ),
    ]
