# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-18 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='position',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
