# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-23 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20201118_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='distance',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='studentposition',
            field=models.CharField(default='null', max_length=1024),
        ),
    ]
