# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-06 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mooc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ming_ma', models.IntegerField(blank=True, default=0, null=True, verbose_name='明码')),
                ('an_ma', models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='暗码')),
                ('time', models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='加入时间')),
                ('is_used', models.CharField(blank=True, default='false', max_length=30, null=True, verbose_name='是否使用')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Number_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
