# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_week', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(verbose_name='消息的详细信息')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_week.CodeWeekClass')),
            ],
        ),
    ]
