# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2025-02-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_week', '0002_latestinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeweekclass',
            name='numberEachProblem',
            field=models.IntegerField(choices=[(1, '一个题目最多只能分配给1个小组'), (2, '一个题目最多只能分配给2个小组'), (3, '一个题目最多只能分配给3个小组')], default=2),
        ),
    ]
