# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2025-02-25 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_week', '0003_codeweekclass_numbereachproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedirhistory',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Code_history', to='code_week.CodeWeekClassGroup'),
        ),
        migrations.AlterField(
            model_name='codeweekclass',
            name='numberEachProblem',
            field=models.IntegerField(choices=[(0, '不限次数'), (1, '一个题目最多只能分配给1个小组'), (2, '一个题目最多只能分配给2个小组'), (3, '一个题目最多只能分配给3个小组')], default=2),
        ),
    ]
